// DEMO DATA — Replace with your actual products in the admin dashboard
// These are placeholder products for development purposes only

import type { Product } from "@/types";

export const demoProducts: Product[] = [
  {
    id: "demo-001",
    name: "Professional Trinocular Stereo Microscope",
    slug: "professional-trinocular-stereo-microscope",
    sku: "DEMO-MICRO-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Professional stereo microscope for display inspection and panel-level repair work.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Trinocular head for camera attachment",
      "Wide zoom range",
      "Adjustable stand",
      "Compatible with various camera systems",
    ],
    applications: ["LCD panel inspection", "COF repair work", "Display component inspection", "Board-level diagnostics"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: true,
    isDemo: true,
    category: { id: "cat-001", name: "COFS", slug: "cofs", description: null, image: null, sortOrder: 1, isActive: true },
    brand: null,
    specs: [
      { id: "spec-001", name: "Magnification", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Optics" },
      { id: "spec-002", name: "Working Distance", value: "Specification not provided", unit: null, sortOrder: 2, groupName: "Optics" },
    ],
    inventory: { quantity: 10, reserved: 0, lowStockThreshold: 3 },
    reviews: [],
    tags: ["microscope", "stereo", "trinocular", "display repair"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-002",
    name: "LVDS Display Cable — High Resolution",
    slug: "lvds-display-cable-high-resolution",
    sku: "DEMO-LVDS-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "LVDS cable for LCD and LED display signal connections and panel repair.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "High-quality signal transmission",
      "Multiple connector options",
      "Compatible with leading display panels",
      "Reliable connection",
    ],
    applications: ["LCD display repair", "LED panel repair", "Display board replacement", "Signal connection"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: true,
    isDemo: true,
    category: { id: "cat-002", name: "LVDS", slug: "lvds", description: null, image: null, sortOrder: 2, isActive: true },
    brand: null,
    specs: [
      { id: "spec-010", name: "Connector Type", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Connectivity" },
      { id: "spec-011", name: "Pin Count", value: "Specification not provided", unit: null, sortOrder: 2, groupName: "Connectivity" },
    ],
    inventory: { quantity: 8, reserved: 0, lowStockThreshold: 3 },
    reviews: [],
    tags: ["LVDS", "display cable", "LCD", "LED"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-003",
    name: "Head Assembly — Display Bonding",
    slug: "head-assembly-display-bonding",
    sku: "DEMO-HEAD-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Head assembly for professional COF bonding and display panel repair work.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Precision bonding head",
      "Compatible with standard bonding equipment",
      "Designed for display panel repair",
      "Professional grade",
    ],
    applications: ["COF bonding", "ACF tape application", "Display panel repair", "Panel bonding work"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: true,
    isDemo: true,
    category: { id: "cat-003", name: "HEAD ASSEMBLY", slug: "head-assembly", description: null, image: null, sortOrder: 9, isActive: true },
    brand: null,
    specs: [
      { id: "spec-020", name: "Bonding Width", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Specifications" },
      { id: "spec-021", name: "Type", value: "Specification not provided", unit: null, sortOrder: 2, groupName: "Specifications" },
    ],
    inventory: { quantity: 15, reserved: 0, lowStockThreshold: 5 },
    reviews: [],
    tags: ["head assembly", "bonding", "COF", "display repair"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-004",
    name: "Precision COF Cutter",
    slug: "precision-cof-cutter",
    sku: "DEMO-COFC-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Precision cutter for COF chip-on-film trimming and display panel preparation.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Precision cutting blade",
      "Designed for COF work",
      "Clean, accurate cuts",
      "Professional grade",
    ],
    applications: ["COF cutting", "Display panel preparation", "LCD/LED panel repair", "COF bonding preparation"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: true,
    isDemo: true,
    category: { id: "cat-004", name: "COF CUTTER", slug: "cof-cutter", description: null, image: null, sortOrder: 12, isActive: true },
    brand: null,
    specs: [
      { id: "spec-030", name: "Blade Type", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Specifications" },
    ],
    inventory: { quantity: 25, reserved: 0, lowStockThreshold: 5 },
    reviews: [],
    tags: ["COF cutter", "precision cutter", "display repair", "COF"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-005",
    name: "COF Chip-on-Film Component",
    slug: "cof-chip-on-film-component",
    sku: "DEMO-COF-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "COF chip-on-film component for LCD and LED display panel repair and bonding.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Compatible with display panel repair",
      "Professional grade COF",
      "For bonding applications",
    ],
    applications: ["COF bonding", "Display panel repair", "LCD/LED repair"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: false,
    isDemo: true,
    category: { id: "cat-007", name: "COFS", slug: "cofs", description: null, image: null, sortOrder: 1, isActive: true },
    brand: null,
    specs: [
      { id: "spec-040", name: "Compatibility", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Specs" },
    ],
    inventory: { quantity: 20, reserved: 0, lowStockThreshold: 5 },
    reviews: [],
    tags: ["COF", "chip on film", "display repair"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-006",
    name: "ACF Remover Solution",
    slug: "acf-remover-solution",
    sku: "DEMO-ACFR-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Professional ACF remover for residue removal from LCD and LED display panels.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Effective ACF residue removal",
      "Safe for display panel substrates",
      "Professional grade formulation",
    ],
    applications: ["ACF residue removal", "Display panel preparation", "COF repair preparation"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: false,
    isDemo: true,
    category: { id: "cat-006", name: "ACF REMOVER", slug: "acf-remover", description: null, image: null, sortOrder: 11, isActive: true },
    brand: null,
    specs: [],
    inventory: { quantity: 50, reserved: 0, lowStockThreshold: 10 },
    reviews: [],
    tags: ["ACF remover", "display repair", "panel repair"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-007",
    name: "T-CON Programmer Tool",
    slug: "t-con-programmer-tool",
    sku: "DEMO-TCP-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Professional T-CON programmer for flashing and repairing T-CON boards in LCD/LED displays.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Supports multiple T-CON board models",
      "Read and write firmware",
      "Board diagnostics",
    ],
    applications: ["T-CON board programming", "Display repair", "Board-level diagnostics", "Firmware restoration"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: false,
    isDemo: true,
    category: { id: "cat-008", name: "T-CON PROGRAMMER", slug: "t-con-programmer", description: null, image: null, sortOrder: 8, isActive: true },
    brand: null,
    specs: [
      { id: "spec-070", name: "Supported Boards", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Specs" },
    ],
    inventory: { quantity: 12, reserved: 0, lowStockThreshold: 3 },
    reviews: [],
    tags: ["T-CON programmer", "display repair", "T-CON board"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-008",
    name: "ACF Tape — Display Panel Bonding",
    slug: "acf-tape-display-panel-bonding",
    sku: "DEMO-ACFT-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Anisotropic conductive film tape for COF bonding and LCD/LED display panel repair.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Anisotropic conductive film",
      "For professional bonding applications",
      "Compatible with display panel substrates",
    ],
    applications: ["COF bonding", "Display panel bonding", "LCD/LED panel repair"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: false,
    isDemo: true,
    category: { id: "cat-009", name: "ACF TAPE", slug: "acf-tape", description: null, image: null, sortOrder: 10, isActive: true },
    brand: null,
    specs: [],
    inventory: { quantity: 30, reserved: 0, lowStockThreshold: 5 },
    reviews: [],
    tags: ["ACF tape", "bonding tape", "COF", "display repair"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export function getFeaturedProducts() {
  return demoProducts.filter((p) => p.isFeatured);
}

export function getProductsByCategory(slug: string) {
  return demoProducts.filter((p) => p.category?.slug === slug);
}

export function getProductBySlug(slug: string) {
  return demoProducts.find((p) => p.slug === slug) || null;
}

export function searchProducts(query: string) {
  const q = query.toLowerCase();
  return demoProducts.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.shortDescription?.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)) ||
      p.category?.name.toLowerCase().includes(q)
  );
}
