// DEMO DATA — Replace with your actual products in the admin dashboard
// These are placeholder products for development purposes only

import type { Product } from "@/types";

export const demoProducts: Product[] = [
  {
    id: "demo-001",
    name: "Professional Trinocular Stereo Microscope",
    slug: "professional-trinocular-stereo-microscope",
    sku: "DEMO-MICRO-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Professional stereo microscope for mobile phone repair and PCB inspection work.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Trinocular head for camera attachment",
      "Wide zoom range",
      "Adjustable stand",
      "Compatible with various camera systems",
    ],
    applications: ["Mobile phone repair", "PCB inspection", "Microsoldering", "BGA work"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: true,
    isDemo: true,
    category: { id: "cat-001", name: "Microscopes", slug: "microscopes", description: null, image: null, sortOrder: 1, isActive: true },
    brand: null,
    specs: [
      { id: "spec-001", name: "Magnification", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Optics" },
      { id: "spec-002", name: "Working Distance", value: "Specification not provided", unit: null, sortOrder: 2, groupName: "Optics" },
    ],
    inventory: { quantity: 10, reserved: 0, lowStockThreshold: 3 },
    reviews: [],
    tags: ["microscope", "stereo", "trinocular", "repair"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-002",
    name: "Digital Microscope Camera — High Resolution",
    slug: "digital-microscope-camera-high-resolution",
    sku: "DEMO-CAM-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "High-resolution camera for microscope integration with PC/Mac compatibility.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "High resolution sensor",
      "USB connectivity",
      "Compatible with leading microscope brands",
      "Software included",
    ],
    applications: ["Microscope documentation", "Live view inspection", "Quality control"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: true,
    isDemo: true,
    category: { id: "cat-002", name: "Microscope Cameras", slug: "microscope-cameras", description: null, image: null, sortOrder: 2, isActive: true },
    brand: null,
    specs: [
      { id: "spec-010", name: "Resolution", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Sensor" },
      { id: "spec-011", name: "Interface", value: "Specification not provided", unit: null, sortOrder: 2, groupName: "Connectivity" },
    ],
    inventory: { quantity: 8, reserved: 0, lowStockThreshold: 3 },
    reviews: [],
    tags: ["camera", "microscope camera", "digital"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-003",
    name: "Precision Soldering Station",
    slug: "precision-soldering-station",
    sku: "DEMO-SOLD-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Temperature-controlled soldering station for fine electronics and microsoldering work.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Precise temperature control",
      "Compatible with multiple tip types",
      "Fast heat-up time",
      "ESD safe design",
    ],
    applications: ["Microsoldering", "PCB rework", "Component replacement", "Electronics assembly"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: true,
    isDemo: true,
    category: { id: "cat-003", name: "Soldering Tools", slug: "soldering-tools", description: null, image: null, sortOrder: 3, isActive: true },
    brand: null,
    specs: [
      { id: "spec-020", name: "Temperature Range", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Performance" },
      { id: "spec-021", name: "Power", value: "Specification not provided", unit: null, sortOrder: 2, groupName: "Performance" },
    ],
    inventory: { quantity: 15, reserved: 0, lowStockThreshold: 5 },
    reviews: [],
    tags: ["soldering", "soldering station", "microsoldering"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-004",
    name: "Precision Screwdriver Set — Mobile Repair",
    slug: "precision-screwdriver-set-mobile-repair",
    sku: "DEMO-SCRW-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Complete precision screwdriver set for mobile phone disassembly and repair work.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Multiple bit sizes included",
      "ESD safe handles",
      "Magnetic tips",
      "Portable case included",
    ],
    applications: ["iPhone repair", "Android repair", "Laptop disassembly", "Electronics repair"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: true,
    isDemo: true,
    category: { id: "cat-004", name: "Precision Screwdrivers", slug: "screwdrivers", description: null, image: null, sortOrder: 4, isActive: true },
    brand: null,
    specs: [
      { id: "spec-030", name: "Bits Included", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Contents" },
    ],
    inventory: { quantity: 25, reserved: 0, lowStockThreshold: 5 },
    reviews: [],
    tags: ["screwdriver", "precision", "mobile repair", "set"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-005",
    name: "PCB Repair Power Boot Cable",
    slug: "pcb-repair-power-boot-cable",
    sku: "DEMO-CABLE-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Diagnostic power boot cable for mobile device PCB testing and repair.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Compatible with multiple device models",
      "Direct boot capability",
      "Diagnostic use",
    ],
    applications: ["PCB diagnosis", "Device repair", "Boot testing"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: false,
    isDemo: true,
    category: { id: "cat-007", name: "Repair Cables", slug: "repair-cables", description: null, image: null, sortOrder: 7, isActive: true },
    brand: null,
    specs: [
      { id: "spec-040", name: "Compatibility", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Specs" },
    ],
    inventory: { quantity: 20, reserved: 0, lowStockThreshold: 5 },
    reviews: [],
    tags: ["cable", "boot cable", "PCB repair"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-006",
    name: "Anti-Static Cleaning Brush Set",
    slug: "anti-static-cleaning-brush-set",
    sku: "DEMO-CLEAN-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Professional anti-static brushes for PCB and electronics cleaning.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "ESD safe bristles",
      "Multiple sizes included",
      "Solvent resistant",
    ],
    applications: ["PCB cleaning", "Component cleaning", "Workshop maintenance"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: false,
    isDemo: true,
    category: { id: "cat-006", name: "Cleaning Tools", slug: "cleaning-tools", description: null, image: null, sortOrder: 6, isActive: true },
    brand: null,
    specs: [],
    inventory: { quantity: 50, reserved: 0, lowStockThreshold: 10 },
    reviews: [],
    tags: ["cleaning", "brush", "anti-static"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-007",
    name: "Digital Multimeter — Professional Grade",
    slug: "digital-multimeter-professional-grade",
    sku: "DEMO-LAB-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Professional digital multimeter for electronics lab and repair diagnostics.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "Auto-ranging",
      "Large backlit display",
      "Multiple measurement modes",
    ],
    applications: ["Electronics diagnostics", "Component testing", "Voltage measurement"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: false,
    isDemo: true,
    category: { id: "cat-008", name: "Lab Tools", slug: "lab-tools", description: null, image: null, sortOrder: 8, isActive: true },
    brand: null,
    specs: [
      { id: "spec-070", name: "Measurement Range", value: "Specification not provided", unit: null, sortOrder: 1, groupName: "Specs" },
    ],
    inventory: { quantity: 12, reserved: 0, lowStockThreshold: 3 },
    reviews: [],
    tags: ["multimeter", "lab", "diagnostic"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-008",
    name: "ESD Safe Tweezers Set",
    slug: "esd-safe-tweezers-set",
    sku: "DEMO-ACC-001",
    description: "This is a demo product. Please replace with your actual product details in the admin panel.",
    shortDescription: "Anti-static tweezers for precision work on mobile phones and PCBs.",
    price: null,
    salePrice: null,
    status: "published",
    stockStatus: "in_stock",
    images: [],
    features: [
      "ESD safe material",
      "Multiple tip profiles",
      "Stainless steel construction",
    ],
    applications: ["Component placement", "SMD work", "Mobile repair"],
    compatibility: [],
    whatsIncluded: [],
    warranty: null,
    isFeatured: false,
    isDemo: true,
    category: { id: "cat-009", name: "Accessories", slug: "accessories", description: null, image: null, sortOrder: 9, isActive: true },
    brand: null,
    specs: [],
    inventory: { quantity: 30, reserved: 0, lowStockThreshold: 5 },
    reviews: [],
    tags: ["tweezers", "ESD", "accessories"],
    viewCount: 0,
    saleCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export function getFeaturedProducts() {
  return demoProducts.filter((p) => p.isFeatured);
}

export function getProductsByCategory(slug: string) {
  return demoProducts.filter((p) => p.category?.slug === slug);
}

export function getProductBySlug(slug: string) {
  return demoProducts.find((p) => p.slug === slug) || null;
}

export function searchProducts(query: string) {
  const q = query.toLowerCase();
  return demoProducts.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.shortDescription?.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)) ||
      p.category?.name.toLowerCase().includes(q)
  );
}
